# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    working_directory: ~/i18n-book-ng
    docker:
      - image: cimg/node:12.19.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: i18n-book-ng-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: i18n-book-ng-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: |
          npm run build
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  build:
    # Run the welcome/run job in its own container
    jobs:
      - build

